### ISSUE TITLE
Add RobotoDraft fonts

### ISSUE THREAD

**Issue by mprentic-harris** [FontFaceKit/roboto#2]
Is it possible to use the RobotoDraft fonts in this repo or in another similar repo?

Thank you.

**Comment by bardware** [comment]
I took the font files from this [hg repository](https://code.google.com/p/googlefontdirectory/source/browse/#hg%2Fapache)
I don't see `robotodraft` there.

**Comment by mprentic-harris** [comment]
Yeah, I don't see it there or on Google Fonts.

Maybe this will help though: https://fonts.googleapis.com/css?family=RobotoDraft:400,500,700,400italic

**Comment by bardware** [comment]
I added the RobotoDraft font to an [individual repository](https://github.com/FontFaceKit/robotodraft)
I downloaded the woff2 files and decompressed them with the google/woff2 tool to ttf files. Sass files as in other repositories.
I know nothing about the license of the font, so no additional files there.

**Comment by mprentic-harris** [comment]
@bardware Very cool! Thank you.

**Comment by sebastian-65** [comment]
@bardware Thank you very much, Sir!
