### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by stefan-schweiger** [FontFaceKit/roboto#3]
Seems like you are not using the latest version of Roboto, because when you download the ttf files from google fonts the file sizes differ (145kb vs 159kb for Roboto-Regular.ttf).

Also see this entry:

https://www.google.com/fonts/specimen/Roboto

> **Updated January 14 2015:** Christian Robertson and the Material Design team unveiled the latest version of Roboto at Google I/O last year, and it is now available from Google Fonts. Existing websites using Roboto via Google Fonts will start using the latest version automatically. If you have installed the fonts on your computer, please download them again and re-install.

**Comment by bardware** [comment]
I hope everything's fine. I took the [`.ttf` files](https://github.com/google/fonts/tree/master/apache/roboto), converted them to `.woff` and `.woff2`, increased the version in the `.css` file and packed a release.
