### ISSUE TITLE
condensed font

### ISSUE THREAD

**Issue by DanielRuf** [FontFaceKit/roboto#9]
Is it planned to add the condensed font or can you recommend a repository for the condensed webfont?

**Comment by DanielRuf** [comment]
Bump.

**Comment by bardware** [comment]
Hi Daniel,

I guess I underestimate the impact of these repos. It seems I inherited this github project.
I made RobotoCondensed available in a [repo](https://github.com/FontFaceKit/robotocondensed).

Hope it helps.
Bernhard

**Comment by DanielRuf** [comment]
Awesome, thanks for your effort and this extra repository.
